{{- if .Values.relay.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-relay
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.relay.labels" . | nindent 4 }}
  {{- with .Values.relay.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.relay.service.type }}
  externalTrafficPolicy: {{ .Values.relay.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.relay.service.port }}
      targetPort: quic
      protocol: UDP
      name: quic
    - port: {{ .Values.relay.service.stunPort }}
      targetPort: stun
      protocol: UDP
      name: stun
    {{- if .Values.relay.metrics.enabled }}
    - port: {{ .Values.relay.metrics.port}}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "netbird.relay.selectorLabels" . | nindent 4 }}
  {{- with .Values.relay.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
